[profile.default]
libs = ["lib"]
out = "out"
solc-version = "0.8.16"
src = "src"
test = "test"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
arbitrumOne = "${ARBITRUM_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
arbitrumOne = {key = "${SCAN_API_KEY}", url = "https://api.arbiscan.io/api"}
arbitrumSepolia = {key = "${SCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api"}
