[profile.default]
evm_version = "cancun"
fs_permissions = [{access = "read-write", path = "./"}]
libs = ["lib"]
out = "out"
solc-version = "0.8.24"
src = "src"
test = "test"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
arbitrumOne = "${ARB_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
arbitrumOne = {key = "${ARB_API_KEY}", url = "https://api.arbiscan.io/api"}
arbitrumSepolia = {key = "${ARB_SEP_API_KEY}", url = "https://api-sepolia.arbiscan.io/api"}
sepolia = {key = "${SEPOLIA_API_KEY}", url = "https://api-sepolia.etherscan.io/api"}
